### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tr4g** [efossier/youtube-mp3#5]
Tried using:
```
youtube-mp3 "https://www.youtube.com/watch?v=L0MK7qz13bU"
```
I get:

> ERROR: Unable to fetch video metadata from youtube.
> Error: Error parsing config: Unexpected token ; in JSON at position 73737
>     at gotConfig (/home/seb/youtube-mp3/node_modules/ytdl-core/lib/info.js:123:21)
>     at /home/seb/youtube-mp3/node_modules/ytdl-core/lib/info.js:74:7
>     at PassThrough.<anonymous> (/home/seb/youtube-mp3/node_modules/miniget/dist/index.js:215:32)
>     at PassThrough.emit (events.js:314:20)
>     at endReadableNT (_stream_readable.js:1244:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by efossier** [comment]
Check out https://github.com/efossier/youtube-mp3/issues/4

This happens pretty frequently and I need to bump the version of ytdl. I'll do so when I have some time, but this should provide a workaround in the meantime.

**Comment by efossier** [comment]
works on the most recent version
